---
# tasks file for common_apt_install
- name: aptインストール
  ansible.builtin.yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: "{{ item.update_cache }}"
  with_items: "{{ apt_install }}"

